import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
import {localDB} from './local-db.mjs';
const DB=localDB(),env={DB,STATUS_REPORT_TOKEN:'local-test-only'};
const call=(path,method='GET',body,headers={})=>worker.fetch(new Request('https://local.test'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined}),env,{});
const reportHeaders={'X-Status-Token':env.STATUS_REPORT_TOKEN};
assert.equal((await call('/api/snapshot')).status,401);
assert.equal((await call('/api/report/node','POST',{server_name:'test',gpus:[]})).status,401);
assert.equal((await call('/api/report/node','POST',{},reportHeaders)).status,400);
assert.equal((await call('/api/report/slurm','POST',{squeue:[]},reportHeaders)).status,400);
assert.equal((await call('/api/report/slurm')).status,405);
const node={server_name:'unit-node',cpu_percent:12,gpus:[{id:0,gpu_name:'A6000',gpu_utilization:0,vram_total_mb:49152,vram_total_used_mb:0,processes:[]},{id:1,collection_error:'NVML read failed',processes:[]}]};
assert.equal((await call('/api/report/node','POST',node,reportHeaders)).status,200);
assert.equal((await call('/api/report/slurm','POST',{sinfo:[],squeue:[],accounting:{jobs:[]}},reportHeaders)).status,200);
let snapshot=await (await call('/api/snapshot','GET',null,{'oai-authenticated-user-id':'test'})).json();
assert.equal(snapshot.nodes.length,1);assert.equal(snapshot.nodes[0].data.gpus[0].gpu_utilization,0);assert.equal(snapshot.nodes[0].data.gpus[1].gpu_utilization,null);assert.equal(snapshot.history[0].utilization,0);assert.equal(snapshot.history[0].gpu_count,1);
node.gpus[0].gpu_utilization=50;await call('/api/report/node','POST',node,reportHeaders);snapshot=await(await call('/api/snapshot','GET',null,{'oai-authenticated-user-id':'test'})).json();assert.equal(snapshot.nodes.length,1);assert.equal(snapshot.history.length,1);assert.equal(snapshot.history[0].utilization,50);
const failure=await worker.fetch(new Request('https://local.test/api/snapshot',{headers:{'oai-authenticated-user-id':'test'}}),{DB:{prepare(){throw new Error('simulated unavailable')}}},{});assert.equal(failure.status,503);
if(process.argv[2]){const real=JSON.parse(readFileSync(process.argv[2],'utf8'));assert.equal((await call('/api/report/node','POST',real.node,reportHeaders)).status,200);assert.equal((await call('/api/report/slurm','POST',real.slurm,reportHeaders)).status,200);snapshot=await(await call('/api/snapshot','GET',null,{'oai-authenticated-user-id':'test'})).json();assert.equal(snapshot.slurm.data.squeue.length,real.slurm.squeue.length);assert.equal(snapshot.nodes.find(n=>n.data.server_name===real.node.server_name).data.gpus.length,real.node.gpus.length);console.log('Real agent fixture: both reports accepted and retrieved.');}
assert.equal((await call('/')).status,200);assert.equal((await call('/api/unknown')).status,404);
console.log('PASS: authentication, input validation, empty jobs, zero vs missing metrics, storage update, minute history, failure handling, assets.');
